#!/usr/bin/env bash

### BEGIN ###
# Author: idevz
# Since: 2018/03/12
# Description:       Build and push WeiboMesh Docker image.
#	User input a build type, program will do the building things:
#	like:
# ./bp.sh bt                             building testing docker image
# ./bp.sh tti                            show image info  ./bp.sh tti
# GOLANG_VERSION=1.9 ./bp.sh bt         build both rpm and docker images with golang 1.9(default)"
### END ###

OR_PREFIX=${OR_PREFIX:-"/usr/local/openresty"}

if [ ! -z ${VALGRIND} ]; then
	export TEST_NGINX_USE_VALGRIND=1
fi

exec ${OR_PREFIX}/bin/openresty -g "daemon off;"
